project:
  type: website
  output-dir: docs

website:
  title: "Ibrahim_ Abdullahi"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: cv.qmd
        text: "{{< fa user-tie >}} CV"
        
    right:
      - href: contact.qmd
        text: "{{< fa envelope >}} Contact"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

