project:
  type: website
  output-dir: docs

website:
  title: "Ibrahim_ Abdullahi"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: cv.qmd
        text: "{{< fa user-tie >}} CV"
        
    right:
      - href: contact.qmd
        text: "{{< fa envelope >}} Contact"
      - href: https://iabdullahi227.github.io/Ibrahim_-Abdullahi/
        icon: github
      - href: https://www.linkedin.com/in/ibrahimabdullahi227me
        icon: linkedin

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

