---
author: "Ibrahim Abdullahi"
title: "Curriculum Vitae"


---


PDF Version [here](docs/Curriculum_Vitae.pdf)
   

## Contact Information

{{< fa envelope >}} [iabdullahi@mun.ca](mailto:iabdullahi@mun.ca)

{{< fa phone >}} (709) 853-5838

{{< fa paper-plane >}}Department of Economics   
&nbsp;&nbsp;&nbsp;&nbsp; Memorial University of Newfoundland and Labrador.  
&nbsp;&nbsp;&nbsp;&nbsp; 230 Elizabeth Avenue   
&nbsp;&nbsp;&nbsp;&nbsp; St.John's, NL, Canada   
&nbsp;&nbsp;&nbsp;&nbsp; A1C 5S7

# Professional Summary

Passionate Economics Master's student skilled in translating economic theories into practical solutions through analytical thinking and quantitative methods. I have a robust foundation in economic modeling, statistical analysis, and empirical research, allowing me to apply theoretical knowledge to real-world economic challenges. I am currently a Research Assistant to Dr. MUstapha Immurana (Senior Research Fellow at University of Health and Allied Sciences (UHAS)) and a Graduate Teaching Assistant at Memorial University of Newfoundland and Labrador(MUN). I have a long-standing experience in teaching. Eager to contribute my academic rigor and analytical expertise to dynamic research or policy-oriented roles in the field of economics. 


# Education

- MA Economics,Memorial University of Newfoundland Labrador, current.
- BA Economics and Insurance (First- class Honors),2021.


# Current Positions

- Graduating Teaching Assistant (2023-), Department of Economics, Memorial University Newfoundland and Labrador (MUN).
- Research Assistant, Dr. Mustapha Immurana, University of Health and Allied Sciences, (UHAS)
- Cashier, Mark's Kelsey Drive.

# Previous Position

- Insurance Broker (Operations), (2023), Safe Haven Insurance Brokers Ltd, Accra, Ghana
- Tutor(2021-2023),A+ Services Group, Accra, Ghana
- Life Assurance Underwriter(2021-2023), Starlife Assurance Company Ltd, Accra, Ghana

# Fields of Interest
- Health Economics
- Labor Economics
- Energy Economics
- Environmental Economics
- Econometrics
- Machine Learning
- Data Analysis

# Conference
- Immurana, M., Kisseih, K.G.,  Abdullahi, I., Azuug, M., Manyeh, A.K., Ayisha Mohammed, A.,  Kizhakkekara, T.J.M. (2023). The effects of selected neglected tropical diseases on economic performance at the macrolevel in Africa. Presentation (virtual) made during the 3rd International Conference on Public Health in Africa, on the 22nd of November, 2023.

# Teaching Services

- *Undergraduate*:
  
  - Economics Help center,Memorial University Newfoundland and Labrador (MUN).
  
  - Introduction to Macroeconomics,Memorial University Newfoundland and Labrador (MUN).
  
  -Introduction to Mathematics For Economists, University of Ghana.
  
  - Introduction to Statistics For Economist, University of Ghana.
  
  - Applied Statistics and Mathematics for Economist, University of Ghana.
  
  - Intermediate Macroeconomics,University of Ghana.
  -Intermediate Microeconomics,University of Ghana.
  
- *Other*:

  - Senior High Economics and Mathematics Tutor (2015-2021).

# Leadership Positions

- Head of Academic Board Committee (Insurance Student Association)
University of Ghana

- Course Representative (University of Ghana ).

- Member of the Academic Board Committee (Student Representative Council).

University of Ghana
- Board Member of Ghana Muslim Student Association (GMSA)
Islamic Senior High School.


# Certifications

- TCPS 2: CORE-2022

- How to write Quality Research paper/thesis ZilLearn

- Introduction to Python Datacamp

- Business Analytics with Excel Simplilearn

- Python for Machine Learning Great Learning

- Data Visualization Great Learning

- Data Analytics Consulting Virtual Internship KPMG

# Technical and Computing Skills

- Microsoft Suite
- Stata
- R
- LaTex
- Quarto
- RMarkdown

# Volunteer Works.

- Volunteered at Sharing Hope Foundation (focuses on reducing teenage pregnancy) as finance
manager.

- Member of Peace Dawah Media. Focuses on helping vulnerable people in the village with foodstuff,
and providing equal opportunities for education for blind people in the country by assisting them
with their educational materials.

- Member of United People Global Sustainable Development (UPG).

- Organized Extra classes for students in my community during covid- 19 during the closure of
schools with strict adherence to the protocols.

# Awards and Scholarships.

- Memorial University Newfoundland and Labrador (MUN), Graduate Scholarship.

- The University of Ghana Academic Award _ Sadhu T.I Vaswani/Indian Association of Ghana
Prize for Economics (2019/2020).
{{< fa youtube>}} [www.youtube.com/watch?v=7WSJIMd8KZM](http://www.youtube.com/watch?v=7WSJIMd8KZM)

- Islamic Senior High Award _ Government Merit Scholarship for the best student (2013-2015)

# Languages
- English
- Arabic (Reading and Writing)
- Ghanaian Language (Twi)
- Hausa




